### PR TITLE
Toasts and screen-reader-only text

### LINKED ISSUE #769: Infinite redirect loop from ADFS
**What Happened**
From user report (thanks @mkewins !):

> "I believe I'm getting caught in a redirect loop when my password is incorrect. I might be using the wrong password for our QA testing account since it was updated recently.

> Redirected back to MOVE and immediately back to the login page, with no error/status message.

**What Should Happen**
> Redirected back to MOVE with an error message saying my password is incorrect, OR the login page says password is incorrect.

**To Reproduce**
On AWS dev:
1. Click on ""Manage Downloads"" in the side nav bar
2. Try and login as ""child\esavage"" (our test account)

### PR DESCRIPTION
**Pull request by candu**
# Issue Addressed
This PR makes significant progress on #791 and #783 , and closes #769 .

# Description
We use `FcToastInfo` in several new places to add notifications of various state / mode changes throughout the application.  We also add `span.sr-only` elements to provide additional context to screen reader users.

In the process, we make progress on saving Track Requests filters across page transitions, and address an infinite-redirect bug when the ADFS login flow fails or is abandoned.

# Tests
Tested quickly in frontend.

### CODE REVIEW

File: lib/Constants.js [hunk 1]
```diff
@@ -183,6 +183,11 @@ HttpStatus.init({
   },
 });
 
+const KeyCode = {
```
Comment (candu) [inline lib/Constants.js:186]: can we document the purpose of this?  in general `Constants` has very little documentation, despite being the most widely used / referred-to module.

File: lib/controller/AuthController.js [hunk 2]
```diff
@@ -96,10 +96,10 @@ AuthController.push({
     try {
       const user = await client.callback(request);
       await login(request, user);
-      return h.redirect(config.PUBLIC_PATH);
+      return h.redirect(`${config.PUBLIC_PATH}?login=1`);
```
Comment (candu) [inline lib/controller/AuthController.js:99]: please document this as well.  the purpose of this flag isn't immediately clear, especially since it works in combination with frontend logic in `LoginState`.

File: lib/requests/RequestDataTableColumns.js [hunk 3]
```diff
@@ -4,7 +4,8 @@
 const RequestDataTableColumns = [
```
Comment (candu) [inline lib/requests/RequestDataTableColumns.js:4]: maybe document this as well?  in particular:

- what does `data-table-expand` do?
- why do we use `text: ''` for some columns, and what are a11y requirements around that?

**Review by candu — COMMENTED** [review]
couple of places that need more documentation, otherwise good
