### PR TITLE
Initial a11y work: axe / WAVE / NVDA 

### LINKED ISSUE #327: Address a11y issues from axe, WAVE, NVDA
**What Happened**
axe and WAVE identified several small issues with accessibility, mostly around non-visual cues and color contrast.

In addition, NVDA surfaced some areas where available text is insufficient (e.g. autocomplete dropdowns).

**What Should Happen**
axe and WAVE should show no errors / warnings, with the exception of those requiring manual review (e.g. contrast of controls over map, where contrast cannot be determined due to `<canvas>` element).

MOVE should be navigable by keyboard, and NVDA should announce meaningful and understandable text for interactive elements.

**To Reproduce**
For axe / WAVE issues:
1. Install axe / WAVE extensions
2. Open MOVE
3. Run axe / WAVE checks on each page within MOVE

For NVDA issues:
1. Install NVDA
2. Open MOVE
3. Use NVDA / keyboard to navigate MOVE

**Additional Notes**
Map accessibility will require a lot of manual work, and can be addressed slightly later (e.g. once we complete the map redesign).

### PR DESCRIPTION
**Pull request by candu**
This PR makes significant progress on #327 by addressing non-contrast-related feedback from axe / WAVE, as well as a couple of nits discovered while testing MOVE under screen reader NVDA.

### CODE REVIEW

File: web/components/FcDetailsStudyRequest.vue [hunk 1]
```diff
@@ -6,9 +6,9 @@
         <v-col cols="8">
           <v-text-field
             v-model="internalValue.serviceRequestId"
+            label="Service Number"
             :messages="[OPTIONAL.text]"
-            outlined
-            placeholder="Service Number">
+            outlined>
```
Comment (candu) [inline web/components/FcDetailsStudyRequest.vue]: realized that we still have a placeholder instead of a label in `FcCommentsStudyRequest`, please fix.
