### PR TITLE
Ped Delay: "beta" copy, info line

### LINKED ISSUE #986: New Request fails to load [dev]
**What Happened**
As reported by @mkewins : when loading the new request flow for any location, the screen remains in a "loading" state indefinitely.

**What Should Happen**
New Request should work as usual.

**To Reproduce**
Steps to reproduce the bug:
1. click into any location on the map
2. from the "View Data" page, click on "Request New"
3. login

**Screenshots**
From dev console:

```
editRequests.js:35 Uncaught (in promise) TypeError: Cannot destructure property 'studyType' of 't' as it is undefined.
    at editRequests.js:35
    at Array.forEach (<anonymous>)
    at $a (editRequests.js:34)
    at editRequests.js:45
    at Array.forEach (<anonymous>)
    at Aa (editRequests.js:44)
    at g.setStudyRequestsForLocationsSelection (editRequests.js:238)
```

**Additional Notes**
This stacktrace corresponds to this function in `vuex` store module `editRequests`:

```js
function getMostRecentByStudyType(studySummaryPerLocation, i) {
  const mostRecentByStudyType = new Map(
    StudyType.enumValues.map(studyType => [studyType, null]),
  );
  studySummaryPerLocation.forEach(({ category, perLocation }) => {
    const { studyType } = category;  // <-- this line here
    const { mostRecent } = perLocation[i];
    mostRecentByStudyType.set(studyType, mostRecent);
  });
  return mostRecentByStudyType;
}
```

It's probably worth another quick search over the codebase to ensure we're not using the deprecated / removed `category` stuff anywhere.

### PR DESCRIPTION
**Pull request by candu**
# Issue Addressed
This PR closes #989 , and closes #986.

# Description
We add `FcTextStudyTypeBeta` and the new `beta` parameter on `StudyType` enum values, to show contextual "beta" copy in various places (View Data, View Reports, global filters drawer).

We also add the new `ReportBlock.INFO` block type, and implement it in `MovePdfGenerator` and `FcReportInfo`.

Finally, we fix a release-blocking bug in Request New, caused by an errant `category` reference.

# Tests
Tested quickly in frontend, using both web and PDF formats, and using both in-beta and not-in-beta study types.

### CODE REVIEW

File: lib/Constants.js [hunk 1]
```diff
@@ -1095,69 +1098,85 @@ StudyType.init({
   ATR_SPEED_VOLUME: {
     label: 'Speed / Volume ATR',
     automatic: true,
+    beta: null,
```
Comment (candu) [inline lib/Constants.js:1101]: add this param to the JSDoc blurb

**Review by candu — COMMENTED** [review]
one small doc change, otherwise good.

**Review by candu — COMMENTED** [review]
LGTM
