### PR TITLE
Fix CSS / layout bug in Track Requests on page resize

### LINKED ISSUE #870: Track Requests Pagination: page number hidden if window size is too small
**What Happened**
The page number selector is pushed down the page (and subsequently hidden) if the window size is too small. No scrollbar to scroll down to see it. (Gotta run, but will update with more details later.)

Screenshot 2021-04-14 172829

**What Should Happen**
A clear and concise description of what you would expect to happen if the bug were fixed.

**To Reproduce**
Steps to reproduce the bug:

**Screenshots**
For frontend bugs, provide a browser screenshot if possible.  For backend bugs, screenshots of either the frontend dev tools (e.g. Network tab showing API responses or errors, Console tab showing errors) or the backend `node --inspect` dev tools (e.g. Debugger tab showing the issue) are helpful.

**Additional Notes**

### PR DESCRIPTION
**Pull request by candu**
# Issue Addressed
This PR closes #870 .

# Description
The table wasn't taking up the proper amount of space - turned out to be a weird interaction between some CSS on the table wrapper component and an `onresize` event handler.

# Tests
Tested quickly in frontend.

### CODE REVIEW

File: web/views/FcRequestsTrack.vue [hunk 1]
```diff
@@ -161,7 +161,7 @@ export default {
   data() {
     return {
       columns: RequestDataTableColumns,
-      heightTable: 400,
+      heightTable: 0,
```
Comment (candu) [inline web/views/FcRequestsTrack.vue]: we don't need this property anymore, get rid of it

**Review by candu — COMMENTED** [review]
one small change, otherwise good

**Review by candu — COMMENTED** [review]
LGTM
